### ISSUE TITLE
Issues when installing the API project

### ISSUE THREAD

**Issue by salsacida** [5GinFIRE/eu.5ginfire.portal.api#74] opened 2019-03-22 16:23 UTC
Following the steps in eu.5ginfire.portal.api’s README.md to execute the portal, I found that some names in repositories had been changed. To install eu.5ginFIRE.riftioyangschema2java and nfv-requirements-extractor with maven I found the names and I updated them accordingly. Now I’m trying to install eu.5ginfire.portal.api but I couldn’t found new missing dependencies.  

After running the following command in the api project:
mvn clean -Pjetty.integration jetty:run

we receive the following error “ Cannot access ${nexusRepositories}/snapshots “

Any help will be much appreciated.
Thanks and best regards,
Miguel

**Comment by ctranoris** [comment] 2019-03-22 17:49
Hi Miguel,
check also:
[eu.5ginfire.nbi.osm4java](https://github.com/5GinFIRE/eu.5ginfire.nbi.osm4java )

Install eu.5ginfire.nbi.osm4java project. Get into the project and run
`mvn clean install`

and let us know.
(I updated the readme)

What is the context for trying the portal api?

**Comment by salsacida** [comment] 2019-03-26 08:58
Hi,
I'm making a similar portal for 5geve project and your portal has a lot of things that I need so I wanted to test if i could include some of this things.
Now it is running OK thank you so much for the quick response and best regards.
Miguel.

**Comment by Ioannischatzis** [comment] 2019-04-11 13:55
Closing this as the issue is fixed.

**Closed by Ioannischatzis** 2019-04-11 13:55 UTC
